package com.austinv11.discordbotinstaller;

public enum ErrorCodes {
	OK, BAD_JAVA_VERSION, UNKNOWN_OS, UNKNOWN_EXCEPTION, CONNECTION_ERROR, FILE_READ_ERROR, FILE_WRITE_ERROR, UNRESOLVED_DEPENDENCY
}
